plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Role: app

hostnames:
  - instance-id

compose:
  ansible_connection: "'aws_ssm'"
  ansible_user: "'ec2-user'"
  ansible_aws_ssm_region: "'us-east-1'"