plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Role: app

hostnames:
  - instance-id

compose:
  ansible_connection: "'amazon.aws.aws_ssm'"
  ansible_aws_ssm_region: "'us-east-1'"
  ansible_user: "'ec2-user'"
  ansible_shell_type: "'sh'"

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""