---
- name: Pre-Deployment Setup (Docker & Config)
  hosts: webserver
  become: true
  tasks:
    - name: Install Docker & docker compose plugin
      dnf:
        name: docker
        state: present
    - name: Create Docker cli-plugins directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Download Docker Compose Binary
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Create a symlink for docker-compose (Optional but helpful)
      file:
        src: /usr/local/lib/docker/cli-plugins/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Start and Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure ec2-user is in docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Create App Directory
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy Docker Compose file
      copy:
        src: files/docker-compose.yml
        dest: /home/ec2-user/app/docker-compose.yml
        owner: ec2-user
        group: ec2-user

    - name: Copy Nginx Config
      copy:
        src: files/nginx.conf
        dest: /home/ec2-user/app/nginx.conf
        owner: ec2-user
        group: ec2-user

    - name: Copy .env file from local to remote
      copy:
        src: ../.env  
        dest: /home/ec2-user/app/.env
        mode: '0600'
        owner: ec2-user
        group: ec2-user